# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_auto_20170301_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
