# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_auto_20170302_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plusone',
            field=models.BooleanField(default=False),
        ),
    ]
